import { execFile } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { promisify } from 'node:util'
import { expect, test } from '@playwright/test'

const execFileAsync = promisify(execFile)
const fixtureCommand = fileURLToPath(new URL('../../scripts/e2e/fixture-command.mjs', import.meta.url))

test.use({ channel: 'chrome' })

test.beforeEach(async () => {
  await execFileAsync(process.execPath, [fixtureCommand, 'reset'], { env: process.env, timeout: 120_000 })
})

test('Company switching isolates Overview projects, tasks, and activity', async ({ page }, testInfo) => {
  const unique = Date.now()
  const companyA = `QA Alpha ${unique}`
  const companyB = `QA Beta ${unique}`
  const projectA = `Alpha Project ${unique}`
  const projectB = `Beta Project ${unique}`
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/sign-in', { waitUntil: 'domcontentloaded' })
  const demoButton = page.getByRole('button', { name: 'Use Hasan Demo' })
  await expect(demoButton).toBeVisible({ timeout: 60_000 })
  await expect.poll(() => page.evaluate(() => window.localStorage.getItem('better-auth_session_data')), { timeout: 60_000 }).toBe('null')
  await demoButton.click()
  await expect.poll(() => page.url(), { timeout: 60_000 }).toMatch(/\/workspace/)

  const navigation = page.getByRole('navigation', { name: 'Company workspace' })
  const onboardingName = page.getByRole('textbox', { name: 'Company name' })
  await expect(onboardingName.or(navigation).first()).toBeVisible({ timeout: 60_000 })
  if (await onboardingName.isVisible()) {
    await onboardingName.fill(companyA)
    await page.getByRole('textbox', { name: 'Private handle' }).fill(`qa-alpha-${unique}`)
    await page.getByRole('button', { name: 'Create Company' }).click()
  } else {
    await navigation.getByRole('link', { name: 'Settings' }).click()
    await page.locator('.company-settings-create-company').getByRole('button', { name: 'Create Company' }).click()
    const createDialog = page.getByRole('dialog', { name: 'Create another Company' })
    await createDialog.getByRole('textbox', { name: 'Company name' }).fill(companyA)
    await createDialog.getByRole('textbox', { name: 'Private handle' }).fill(`qa-alpha-${unique}`)
    await createDialog.getByRole('button', { name: 'Create Company' }).click()
    await expect(createDialog).toBeHidden()
    await page.getByRole('link', { name: 'Back to companies' }).click()
    await page.getByRole('combobox', { name: 'Representing Company' }).click()
    await page.getByRole('option', { name: companyA }).click()
  }
  await navigation.getByRole('link', { name: 'Overview' }).click()
  await expect(page.locator('.company-dashboard-welcome')).toContainText(companyA)

  await page.getByRole('button', { name: 'New project' }).first().click()
  const projectDialog = page.getByRole('dialog', { name: 'New project' })
  await projectDialog.getByRole('textbox', { name: 'Project name' }).fill(projectA)
  await projectDialog.getByRole('button', { name: 'Create Project' }).click()
  await expect(page.locator('.company-overview-live')).toContainText(projectA)
  await page.getByRole('button', { name: /Create task.*Turn an idea into action/ }).click()
  const projectPicker = page.getByRole('dialog', { name: 'Create task' })
  await projectPicker.getByRole('combobox', { name: 'Task project' }).click()
  await page.getByRole('option', { name: projectA }).click()
  await projectPicker.getByRole('button', { name: 'Continue' }).click()
  const taskDialog = page.getByRole('dialog', { name: 'Create task' })
  await taskDialog.getByRole('textbox', { name: 'Title' }).fill(`Alpha Task ${unique}`)
  await taskDialog.getByRole('button', { name: 'Create task' }).click()
  const overview = page.locator('.company-overview-live')
  await expect(overview.locator('.company-dashboard-stat.amber strong').first()).toHaveText('1')
  await expect(overview.locator('.company-dashboard-activity')).toContainText(projectA)
  await expect(page.locator('.track-toast')).toHaveCount(0, { timeout: 10_000 })
  await page.locator('.company-dashboard-welcome').hover()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('company-overview-1280.png'), fullPage: true })

  await navigation.getByRole('link', { name: 'Settings' }).click()
  await expect(page.getByRole('heading', { name: 'Company profile' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('company-settings-desktop.png') })
  await page.getByRole('button', { name: /Appearance:/ }).click()
  await page.getByRole('menuitemradio', { name: 'Dark' }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.keyboard.press('Escape')
  await expect(page.locator('.track-theme-menu')).toBeHidden()
  await page.screenshot({ path: testInfo.outputPath('company-settings-dark-desktop.png') })
  await page.getByRole('button', { name: 'Assign Project' }).click()
  const assignDialog = page.getByRole('dialog', { name: 'Assign an existing Project' })
  await expect(assignDialog).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('company-settings-assign-dialog-desktop.png') })
  await page.keyboard.press('Escape')
  await expect(assignDialog).toBeHidden()
  const createButton = page.locator('.company-settings-create-company').getByRole('button', { name: 'Create Company' })
  await createButton.click()
  const createDialog = page.getByRole('dialog', { name: 'Create another Company' })
  await expect(createDialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(createDialog).toBeHidden()
  await expect(createButton).toBeFocused()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('company-settings-mobile.png') })
  await page.getByRole('button', { name: 'Close Company' }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Close Company' })).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('company-settings-mobile-bottom.png') })
  await page.setViewportSize({ width: 1280, height: 900 })
  await createButton.click()
  await expect(createDialog).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('company-settings-create-dialog-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(createDialog).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('company-settings-create-dialog-mobile.png') })
  await page.setViewportSize({ width: 1280, height: 720 })
  await createDialog.getByRole('textbox', { name: 'Company name' }).fill(companyB)
  await createDialog.getByRole('textbox', { name: 'Private handle' }).fill(`qa-beta-${unique}`)
  await createDialog.getByRole('button', { name: 'Create Company' }).click()
  await expect(createDialog).toBeHidden()
  await page.getByRole('link', { name: 'Back to companies' }).click()
  await page.getByRole('combobox', { name: 'Representing Company' }).click()
  await page.getByRole('option', { name: companyB }).click()
  await navigation.getByRole('link', { name: 'Overview' }).click()
  await expect(page.locator('.company-dashboard-welcome')).toContainText(companyB)
  await expect(overview.locator('.company-dashboard-stat.amber strong').first()).toHaveText('0')
  await expect(overview).not.toContainText(projectA)
  await expect(overview.locator('.company-dashboard-activity')).not.toContainText(projectA)

  await page.getByRole('button', { name: 'New project' }).first().click()
  await projectDialog.getByRole('textbox', { name: 'Project name' }).fill(projectB)
  await projectDialog.getByRole('button', { name: 'Create Project' }).click()
  await expect(overview).toContainText(projectB)
  await page.getByRole('combobox', { name: 'Representing Company' }).click()
  await page.getByRole('option', { name: companyA }).click()
  await expect(page.locator('.company-dashboard-welcome')).toContainText(companyA)
  await expect(overview.locator('.company-dashboard-stat.amber strong').first()).toHaveText('1')
  await expect(overview).toContainText(projectA)
  await expect(overview).not.toContainText(projectB)
  await navigation.getByRole('link', { name: 'People' }).click()
  const invitationEmail = `qa-invite-${unique}@example.test`
  await page.getByRole('textbox', { name: 'Email' }).fill(invitationEmail)
  await page.getByRole('button', { name: 'Invite member' }).click()
  const invitation = page.getByRole('listitem').filter({ hasText: invitationEmail })
  await expect(invitation).toBeVisible()
  await invitation.getByRole('button', { name: 'Revoke' }).click()
  await expect(invitation).toBeHidden()
  expect(pageErrors).toEqual([])
})
