/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceProjectsProjectIdRouteImport } from './routes/workspace.projects.$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceProjectsProjectIdIndexRouteImport } from './routes/workspace.projects.$projectId.index'
import { Route as WorkspaceProjectsProjectIdGroupsGroupIdRouteImport } from './routes/workspace.projects.$projectId.groups.$groupId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectsProjectIdIndexRoute =
  WorkspaceProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceProjectsProjectIdRoute,
  } as any)
const WorkspaceProjectsProjectIdGroupsGroupIdRoute =
  WorkspaceProjectsProjectIdGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => WorkspaceProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/two-factor': typeof TwoFactorRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRouteWithChildren
  '/workspace/projects/$projectId/': typeof WorkspaceProjectsProjectIdIndexRoute
  '/workspace/projects/$projectId/groups/$groupId': typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/two-factor': typeof TwoFactorRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdIndexRoute
  '/workspace/projects/$projectId/groups/$groupId': typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/two-factor': typeof TwoFactorRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRouteWithChildren
  '/workspace/projects/$projectId/': typeof WorkspaceProjectsProjectIdIndexRoute
  '/workspace/projects/$projectId/groups/$groupId': typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/sign-in'
    | '/two-factor'
    | '/workspace'
    | '/api/auth/$'
    | '/workspace/projects/$projectId'
    | '/workspace/projects/$projectId/'
    | '/workspace/projects/$projectId/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/sign-in'
    | '/two-factor'
    | '/workspace'
    | '/api/auth/$'
    | '/workspace/projects/$projectId'
    | '/workspace/projects/$projectId/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/sign-in'
    | '/two-factor'
    | '/workspace'
    | '/api/auth/$'
    | '/workspace/projects/$projectId'
    | '/workspace/projects/$projectId/'
    | '/workspace/projects/$projectId/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  TwoFactorRoute: typeof TwoFactorRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/projects/$projectId': {
      id: '/workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workspace/projects/$projectId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/projects/$projectId/': {
      id: '/workspace/projects/$projectId/'
      path: '/'
      fullPath: '/workspace/projects/$projectId/'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsProjectIdRoute
    }
    '/workspace/projects/$projectId/groups/$groupId': {
      id: '/workspace/projects/$projectId/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/workspace/projects/$projectId/groups/$groupId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdGroupsGroupIdRouteImport
      parentRoute: typeof WorkspaceProjectsProjectIdRoute
    }
  }
}

interface WorkspaceProjectsProjectIdRouteChildren {
  WorkspaceProjectsProjectIdIndexRoute: typeof WorkspaceProjectsProjectIdIndexRoute
  WorkspaceProjectsProjectIdGroupsGroupIdRoute: typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}

const WorkspaceProjectsProjectIdRouteChildren: WorkspaceProjectsProjectIdRouteChildren =
  {
    WorkspaceProjectsProjectIdIndexRoute: WorkspaceProjectsProjectIdIndexRoute,
    WorkspaceProjectsProjectIdGroupsGroupIdRoute:
      WorkspaceProjectsProjectIdGroupsGroupIdRoute,
  }

const WorkspaceProjectsProjectIdRouteWithChildren =
  WorkspaceProjectsProjectIdRoute._addFileChildren(
    WorkspaceProjectsProjectIdRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  TwoFactorRoute: TwoFactorRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
