/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInOptionBRouteImport } from './routes/sign-in-option-b'
import { Route as SignInOptionARouteImport } from './routes/sign-in-option-a'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding.profile'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as WorkspaceProjectsProjectIdRouteImport } from './routes/workspace.projects.$projectId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as WorkspaceProjectsProjectIdIndexRouteImport } from './routes/workspace.projects.$projectId.index'
import { Route as WorkspaceProjectsProjectIdSettingsRouteImport } from './routes/workspace.projects.$projectId.settings'
import { Route as WorkspaceProjectsProjectIdRecordsRouteImport } from './routes/workspace.projects.$projectId.records'
import { Route as WorkspaceProjectsProjectIdGroupsGroupIdRouteImport } from './routes/workspace.projects.$projectId.groups.$groupId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInOptionBRoute = SignInOptionBRouteImport.update({
  id: '/sign-in-option-b',
  path: '/sign-in-option-b',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInOptionARoute = SignInOptionARouteImport.update({
  id: '/sign-in-option-a',
  path: '/sign-in-option-a',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/onboarding/profile',
  path: '/onboarding/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceProjectsProjectIdIndexRoute =
  WorkspaceProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceProjectsProjectIdRoute,
  } as any)
const WorkspaceProjectsProjectIdSettingsRoute =
  WorkspaceProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkspaceProjectsProjectIdRoute,
  } as any)
const WorkspaceProjectsProjectIdRecordsRoute =
  WorkspaceProjectsProjectIdRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => WorkspaceProjectsProjectIdRoute,
  } as any)
const WorkspaceProjectsProjectIdGroupsGroupIdRoute =
  WorkspaceProjectsProjectIdGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => WorkspaceProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-option-a': typeof SignInOptionARoute
  '/sign-in-option-b': typeof SignInOptionBRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRouteWithChildren
  '/workspace/projects/$projectId/records': typeof WorkspaceProjectsProjectIdRecordsRoute
  '/workspace/projects/$projectId/settings': typeof WorkspaceProjectsProjectIdSettingsRoute
  '/workspace/projects/$projectId/': typeof WorkspaceProjectsProjectIdIndexRoute
  '/workspace/projects/$projectId/groups/$groupId': typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-option-a': typeof SignInOptionARoute
  '/sign-in-option-b': typeof SignInOptionBRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/workspace': typeof WorkspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/projects/$projectId/records': typeof WorkspaceProjectsProjectIdRecordsRoute
  '/workspace/projects/$projectId/settings': typeof WorkspaceProjectsProjectIdSettingsRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdIndexRoute
  '/workspace/projects/$projectId/groups/$groupId': typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-in-option-a': typeof SignInOptionARoute
  '/sign-in-option-b': typeof SignInOptionBRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
  '/workspace/': typeof WorkspaceIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRouteWithChildren
  '/workspace/projects/$projectId/records': typeof WorkspaceProjectsProjectIdRecordsRoute
  '/workspace/projects/$projectId/settings': typeof WorkspaceProjectsProjectIdSettingsRoute
  '/workspace/projects/$projectId/': typeof WorkspaceProjectsProjectIdIndexRoute
  '/workspace/projects/$projectId/groups/$groupId': typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/profile'
    | '/sign-in'
    | '/sign-in-option-a'
    | '/sign-in-option-b'
    | '/terms'
    | '/two-factor'
    | '/workspace'
    | '/auth/callback'
    | '/onboarding/profile'
    | '/workspace/'
    | '/api/auth/$'
    | '/workspace/projects/$projectId'
    | '/workspace/projects/$projectId/records'
    | '/workspace/projects/$projectId/settings'
    | '/workspace/projects/$projectId/'
    | '/workspace/projects/$projectId/groups/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/profile'
    | '/sign-in'
    | '/sign-in-option-a'
    | '/sign-in-option-b'
    | '/terms'
    | '/two-factor'
    | '/auth/callback'
    | '/onboarding/profile'
    | '/workspace'
    | '/api/auth/$'
    | '/workspace/projects/$projectId/records'
    | '/workspace/projects/$projectId/settings'
    | '/workspace/projects/$projectId'
    | '/workspace/projects/$projectId/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/profile'
    | '/sign-in'
    | '/sign-in-option-a'
    | '/sign-in-option-b'
    | '/terms'
    | '/two-factor'
    | '/workspace'
    | '/auth/callback'
    | '/onboarding/profile'
    | '/workspace/'
    | '/api/auth/$'
    | '/workspace/projects/$projectId'
    | '/workspace/projects/$projectId/records'
    | '/workspace/projects/$projectId/settings'
    | '/workspace/projects/$projectId/'
    | '/workspace/projects/$projectId/groups/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignInOptionARoute: typeof SignInOptionARoute
  SignInOptionBRoute: typeof SignInOptionBRoute
  TermsRoute: typeof TermsRoute
  TwoFactorRoute: typeof TwoFactorRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-option-b': {
      id: '/sign-in-option-b'
      path: '/sign-in-option-b'
      fullPath: '/sign-in-option-b'
      preLoaderRoute: typeof SignInOptionBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in-option-a': {
      id: '/sign-in-option-a'
      path: '/sign-in-option-a'
      fullPath: '/sign-in-option-a'
      preLoaderRoute: typeof SignInOptionARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/onboarding/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/projects/$projectId': {
      id: '/workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/workspace/projects/$projectId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/projects/$projectId/': {
      id: '/workspace/projects/$projectId/'
      path: '/'
      fullPath: '/workspace/projects/$projectId/'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdIndexRouteImport
      parentRoute: typeof WorkspaceProjectsProjectIdRoute
    }
    '/workspace/projects/$projectId/settings': {
      id: '/workspace/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/workspace/projects/$projectId/settings'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdSettingsRouteImport
      parentRoute: typeof WorkspaceProjectsProjectIdRoute
    }
    '/workspace/projects/$projectId/records': {
      id: '/workspace/projects/$projectId/records'
      path: '/records'
      fullPath: '/workspace/projects/$projectId/records'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRecordsRouteImport
      parentRoute: typeof WorkspaceProjectsProjectIdRoute
    }
    '/workspace/projects/$projectId/groups/$groupId': {
      id: '/workspace/projects/$projectId/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/workspace/projects/$projectId/groups/$groupId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdGroupsGroupIdRouteImport
      parentRoute: typeof WorkspaceProjectsProjectIdRoute
    }
  }
}

interface WorkspaceProjectsProjectIdRouteChildren {
  WorkspaceProjectsProjectIdRecordsRoute: typeof WorkspaceProjectsProjectIdRecordsRoute
  WorkspaceProjectsProjectIdSettingsRoute: typeof WorkspaceProjectsProjectIdSettingsRoute
  WorkspaceProjectsProjectIdIndexRoute: typeof WorkspaceProjectsProjectIdIndexRoute
  WorkspaceProjectsProjectIdGroupsGroupIdRoute: typeof WorkspaceProjectsProjectIdGroupsGroupIdRoute
}

const WorkspaceProjectsProjectIdRouteChildren: WorkspaceProjectsProjectIdRouteChildren =
  {
    WorkspaceProjectsProjectIdRecordsRoute:
      WorkspaceProjectsProjectIdRecordsRoute,
    WorkspaceProjectsProjectIdSettingsRoute:
      WorkspaceProjectsProjectIdSettingsRoute,
    WorkspaceProjectsProjectIdIndexRoute: WorkspaceProjectsProjectIdIndexRoute,
    WorkspaceProjectsProjectIdGroupsGroupIdRoute:
      WorkspaceProjectsProjectIdGroupsGroupIdRoute,
  }

const WorkspaceProjectsProjectIdRouteWithChildren =
  WorkspaceProjectsProjectIdRoute._addFileChildren(
    WorkspaceProjectsProjectIdRouteChildren,
  )

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRouteWithChildren
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRouteWithChildren,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignInOptionARoute: SignInOptionARoute,
  SignInOptionBRoute: SignInOptionBRoute,
  TermsRoute: TermsRoute,
  TwoFactorRoute: TwoFactorRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
