/**
 * Static IANA timezone table.
 *
 * Generated at authoring time from `Intl.supportedValuesOf('timeZone')`, with
 * the zone→country mapping taken from `new Intl.Locale('und-<CC>').getTimeZones()`
 * and country names from `Intl.DisplayNames`. Flags are the two ISO 3166-1
 * alpha-2 letters mapped to regional indicator symbols (U+1F1E6 + letter − 'A').
 *
 * The table is committed as plain data so no device work is needed to build it.
 * Offsets and local times are the only values computed at render, because they
 * move with DST and with the clock.
 */

export type Timezone = {
  city: string;
  countryCode: string;
  countryName: string;
  flag: string;
  id: string;
};

const FORMATTER_CACHE = new Map<string, Intl.DateTimeFormat>();

function partsFormatter(timeZone: string) {
  const cached = FORMATTER_CACHE.get(timeZone);
  if (cached) return cached;
  const formatter = new Intl.DateTimeFormat('en-US', {
    day: '2-digit',
    hour: '2-digit',
    hour12: false,
    minute: '2-digit',
    month: '2-digit',
    second: '2-digit',
    timeZone,
    year: 'numeric',
  });
  FORMATTER_CACHE.set(timeZone, formatter);
  return formatter;
}

/**
 * Current UTC offset of `timeZone` in minutes. Derived by comparing the zone's
 * wall clock against the same instant in UTC, which only relies on
 * `timeZone` support in `Intl.DateTimeFormat`.
 */
export function timezoneOffsetMinutes(timeZone: string, at: Date = new Date()) {
  const parts: Record<string, number> = {};
  for (const { type, value } of partsFormatter(timeZone).formatToParts(at)) {
    if (type !== 'literal') parts[type] = Number(value);
  }
  const hour = parts.hour === 24 ? 0 : parts.hour;
  const wall = Date.UTC(parts.year, parts.month - 1, parts.day, hour, parts.minute, parts.second);
  return Math.round((wall - at.getTime()) / 60_000);
}

/** Human offset such as `UTC+5:30`, `UTC−4`, or `UTC` for the zero offset. */
export function timezoneOffsetLabel(timeZone: string, at: Date = new Date()) {
  const minutes = timezoneOffsetMinutes(timeZone, at);
  if (minutes === 0) return 'UTC';
  const hours = Math.floor(Math.abs(minutes) / 60);
  const rest = Math.abs(minutes) % 60;
  const sign = minutes > 0 ? '+' : '−';
  return rest === 0 ? `UTC${sign}${hours}` : `UTC${sign}${hours}:${String(rest).padStart(2, '0')}`;
}

const TIME_CACHE = new Map<string, Intl.DateTimeFormat>();

/** Current local time in `timeZone`, formatted for the device locale. */
export function timezoneLocalTime(timeZone: string, at: Date = new Date()) {
  let formatter = TIME_CACHE.get(timeZone);
  if (!formatter) {
    formatter = new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit', timeZone });
    TIME_CACHE.set(timeZone, formatter);
  }
  return formatter.format(at);
}

/** The device zone, falling back to UTC when the platform reports nothing. */
export function deviceTimezone() {
  return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
}

export function findTimezone(id: string) {
  return TIMEZONES.find((zone) => zone.id === id);
}

/** Sorted by country name, then city. */
export const TIMEZONES: readonly Timezone[] = [
  { id: 'Asia/Kabul', city: 'Kabul', countryCode: 'AF', countryName: 'Afghanistan', flag: '🇦🇫' },
  { id: 'Europe/Mariehamn', city: 'Mariehamn', countryCode: 'AX', countryName: 'Åland Islands', flag: '🇦🇽' },
  { id: 'Europe/Tirane', city: 'Tirane', countryCode: 'AL', countryName: 'Albania', flag: '🇦🇱' },
  { id: 'Africa/Algiers', city: 'Algiers', countryCode: 'DZ', countryName: 'Algeria', flag: '🇩🇿' },
  { id: 'Pacific/Pago_Pago', city: 'Pago Pago', countryCode: 'AS', countryName: 'American Samoa', flag: '🇦🇸' },
  { id: 'Europe/Andorra', city: 'Andorra', countryCode: 'AD', countryName: 'Andorra', flag: '🇦🇩' },
  { id: 'Africa/Luanda', city: 'Luanda', countryCode: 'AO', countryName: 'Angola', flag: '🇦🇴' },
  { id: 'America/Anguilla', city: 'Anguilla', countryCode: 'AI', countryName: 'Anguilla', flag: '🇦🇮' },
  { id: 'Antarctica/Casey', city: 'Casey', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Davis', city: 'Davis', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/DumontDUrville', city: 'DumontDUrville', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Mawson', city: 'Mawson', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/McMurdo', city: 'McMurdo', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Palmer', city: 'Palmer', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Rothera', city: 'Rothera', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Syowa', city: 'Syowa', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Troll', city: 'Troll', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'Antarctica/Vostok', city: 'Vostok', countryCode: 'AQ', countryName: 'Antarctica', flag: '🇦🇶' },
  { id: 'America/Antigua', city: 'Antigua', countryCode: 'AG', countryName: 'Antigua & Barbuda', flag: '🇦🇬' },
  { id: 'America/Buenos_Aires', city: 'Buenos Aires', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Catamarca', city: 'Catamarca', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Cordoba', city: 'Cordoba', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Jujuy', city: 'Jujuy', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/La_Rioja', city: 'La Rioja', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Mendoza', city: 'Mendoza', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/Rio_Gallegos', city: 'Rio Gallegos', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/Salta', city: 'Salta', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/San_Juan', city: 'San Juan', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/San_Luis', city: 'San Luis', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/Tucuman', city: 'Tucuman', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'America/Argentina/Ushuaia', city: 'Ushuaia', countryCode: 'AR', countryName: 'Argentina', flag: '🇦🇷' },
  { id: 'Asia/Yerevan', city: 'Yerevan', countryCode: 'AM', countryName: 'Armenia', flag: '🇦🇲' },
  { id: 'America/Aruba', city: 'Aruba', countryCode: 'AW', countryName: 'Aruba', flag: '🇦🇼' },
  { id: 'Australia/Adelaide', city: 'Adelaide', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Brisbane', city: 'Brisbane', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Broken_Hill', city: 'Broken Hill', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Darwin', city: 'Darwin', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Eucla', city: 'Eucla', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Hobart', city: 'Hobart', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Lindeman', city: 'Lindeman', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Lord_Howe', city: 'Lord Howe', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Antarctica/Macquarie', city: 'Macquarie', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Melbourne', city: 'Melbourne', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Perth', city: 'Perth', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Australia/Sydney', city: 'Sydney', countryCode: 'AU', countryName: 'Australia', flag: '🇦🇺' },
  { id: 'Europe/Vienna', city: 'Vienna', countryCode: 'AT', countryName: 'Austria', flag: '🇦🇹' },
  { id: 'Asia/Baku', city: 'Baku', countryCode: 'AZ', countryName: 'Azerbaijan', flag: '🇦🇿' },
  { id: 'America/Nassau', city: 'Nassau', countryCode: 'BS', countryName: 'Bahamas', flag: '🇧🇸' },
  { id: 'Asia/Bahrain', city: 'Bahrain', countryCode: 'BH', countryName: 'Bahrain', flag: '🇧🇭' },
  { id: 'Asia/Dhaka', city: 'Dhaka', countryCode: 'BD', countryName: 'Bangladesh', flag: '🇧🇩' },
  { id: 'America/Barbados', city: 'Barbados', countryCode: 'BB', countryName: 'Barbados', flag: '🇧🇧' },
  { id: 'Europe/Minsk', city: 'Minsk', countryCode: 'BY', countryName: 'Belarus', flag: '🇧🇾' },
  { id: 'Europe/Brussels', city: 'Brussels', countryCode: 'BE', countryName: 'Belgium', flag: '🇧🇪' },
  { id: 'America/Belize', city: 'Belize', countryCode: 'BZ', countryName: 'Belize', flag: '🇧🇿' },
  { id: 'Africa/Porto-Novo', city: 'Porto-Novo', countryCode: 'BJ', countryName: 'Benin', flag: '🇧🇯' },
  { id: 'Atlantic/Bermuda', city: 'Bermuda', countryCode: 'BM', countryName: 'Bermuda', flag: '🇧🇲' },
  { id: 'Asia/Thimphu', city: 'Thimphu', countryCode: 'BT', countryName: 'Bhutan', flag: '🇧🇹' },
  { id: 'America/La_Paz', city: 'La Paz', countryCode: 'BO', countryName: 'Bolivia', flag: '🇧🇴' },
  { id: 'Europe/Sarajevo', city: 'Sarajevo', countryCode: 'BA', countryName: 'Bosnia & Herzegovina', flag: '🇧🇦' },
  { id: 'Africa/Gaborone', city: 'Gaborone', countryCode: 'BW', countryName: 'Botswana', flag: '🇧🇼' },
  { id: 'America/Araguaina', city: 'Araguaina', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Bahia', city: 'Bahia', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Belem', city: 'Belem', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Boa_Vista', city: 'Boa Vista', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Campo_Grande', city: 'Campo Grande', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Cuiaba', city: 'Cuiaba', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Eirunepe', city: 'Eirunepe', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Fortaleza', city: 'Fortaleza', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Maceio', city: 'Maceio', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Manaus', city: 'Manaus', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Noronha', city: 'Noronha', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Porto_Velho', city: 'Porto Velho', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Recife', city: 'Recife', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Rio_Branco', city: 'Rio Branco', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Santarem', city: 'Santarem', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'America/Sao_Paulo', city: 'Sao Paulo', countryCode: 'BR', countryName: 'Brazil', flag: '🇧🇷' },
  { id: 'Indian/Chagos', city: 'Chagos', countryCode: 'IO', countryName: 'British Indian Ocean Territory', flag: '🇮🇴' },
  { id: 'America/Tortola', city: 'Tortola', countryCode: 'VG', countryName: 'British Virgin Islands', flag: '🇻🇬' },
  { id: 'Asia/Brunei', city: 'Brunei', countryCode: 'BN', countryName: 'Brunei', flag: '🇧🇳' },
  { id: 'Europe/Sofia', city: 'Sofia', countryCode: 'BG', countryName: 'Bulgaria', flag: '🇧🇬' },
  { id: 'Africa/Ouagadougou', city: 'Ouagadougou', countryCode: 'BF', countryName: 'Burkina Faso', flag: '🇧🇫' },
  { id: 'Africa/Bujumbura', city: 'Bujumbura', countryCode: 'BI', countryName: 'Burundi', flag: '🇧🇮' },
  { id: 'Asia/Phnom_Penh', city: 'Phnom Penh', countryCode: 'KH', countryName: 'Cambodia', flag: '🇰🇭' },
  { id: 'Africa/Douala', city: 'Douala', countryCode: 'CM', countryName: 'Cameroon', flag: '🇨🇲' },
  { id: 'America/Blanc-Sablon', city: 'Blanc-Sablon', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Cambridge_Bay', city: 'Cambridge Bay', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Coral_Harbour', city: 'Coral Harbour', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Creston', city: 'Creston', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Dawson', city: 'Dawson', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Dawson_Creek', city: 'Dawson Creek', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Edmonton', city: 'Edmonton', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Fort_Nelson', city: 'Fort Nelson', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Glace_Bay', city: 'Glace Bay', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Goose_Bay', city: 'Goose Bay', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Halifax', city: 'Halifax', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Inuvik', city: 'Inuvik', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Iqaluit', city: 'Iqaluit', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Moncton', city: 'Moncton', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Rankin_Inlet', city: 'Rankin Inlet', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Regina', city: 'Regina', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Resolute', city: 'Resolute', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/St_Johns', city: 'St Johns', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Swift_Current', city: 'Swift Current', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Toronto', city: 'Toronto', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Vancouver', city: 'Vancouver', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Whitehorse', city: 'Whitehorse', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'America/Winnipeg', city: 'Winnipeg', countryCode: 'CA', countryName: 'Canada', flag: '🇨🇦' },
  { id: 'Atlantic/Cape_Verde', city: 'Cape Verde', countryCode: 'CV', countryName: 'Cape Verde', flag: '🇨🇻' },
  { id: 'America/Kralendijk', city: 'Kralendijk', countryCode: 'BQ', countryName: 'Caribbean Netherlands', flag: '🇧🇶' },
  { id: 'America/Cayman', city: 'Cayman', countryCode: 'KY', countryName: 'Cayman Islands', flag: '🇰🇾' },
  { id: 'Africa/Bangui', city: 'Bangui', countryCode: 'CF', countryName: 'Central African Republic', flag: '🇨🇫' },
  { id: 'Africa/Ndjamena', city: 'Ndjamena', countryCode: 'TD', countryName: 'Chad', flag: '🇹🇩' },
  { id: 'America/Coyhaique', city: 'Coyhaique', countryCode: 'CL', countryName: 'Chile', flag: '🇨🇱' },
  { id: 'Pacific/Easter', city: 'Easter', countryCode: 'CL', countryName: 'Chile', flag: '🇨🇱' },
  { id: 'America/Punta_Arenas', city: 'Punta Arenas', countryCode: 'CL', countryName: 'Chile', flag: '🇨🇱' },
  { id: 'America/Santiago', city: 'Santiago', countryCode: 'CL', countryName: 'Chile', flag: '🇨🇱' },
  { id: 'Asia/Shanghai', city: 'Shanghai', countryCode: 'CN', countryName: 'China', flag: '🇨🇳' },
  { id: 'Asia/Urumqi', city: 'Urumqi', countryCode: 'CN', countryName: 'China', flag: '🇨🇳' },
  { id: 'Indian/Christmas', city: 'Christmas', countryCode: 'CX', countryName: 'Christmas Island', flag: '🇨🇽' },
  { id: 'Indian/Cocos', city: 'Cocos', countryCode: 'CC', countryName: 'Cocos (Keeling) Islands', flag: '🇨🇨' },
  { id: 'America/Bogota', city: 'Bogota', countryCode: 'CO', countryName: 'Colombia', flag: '🇨🇴' },
  { id: 'Indian/Comoro', city: 'Comoro', countryCode: 'KM', countryName: 'Comoros', flag: '🇰🇲' },
  { id: 'Africa/Brazzaville', city: 'Brazzaville', countryCode: 'CG', countryName: 'Congo - Brazzaville', flag: '🇨🇬' },
  { id: 'Africa/Kinshasa', city: 'Kinshasa', countryCode: 'CD', countryName: 'Congo - Kinshasa', flag: '🇨🇩' },
  { id: 'Africa/Lubumbashi', city: 'Lubumbashi', countryCode: 'CD', countryName: 'Congo - Kinshasa', flag: '🇨🇩' },
  { id: 'Pacific/Rarotonga', city: 'Rarotonga', countryCode: 'CK', countryName: 'Cook Islands', flag: '🇨🇰' },
  { id: 'America/Costa_Rica', city: 'Costa Rica', countryCode: 'CR', countryName: 'Costa Rica', flag: '🇨🇷' },
  { id: 'Africa/Abidjan', city: 'Abidjan', countryCode: 'CI', countryName: 'Côte d’Ivoire', flag: '🇨🇮' },
  { id: 'Europe/Zagreb', city: 'Zagreb', countryCode: 'HR', countryName: 'Croatia', flag: '🇭🇷' },
  { id: 'America/Havana', city: 'Havana', countryCode: 'CU', countryName: 'Cuba', flag: '🇨🇺' },
  { id: 'America/Curacao', city: 'Curacao', countryCode: 'CW', countryName: 'Curaçao', flag: '🇨🇼' },
  { id: 'Asia/Famagusta', city: 'Famagusta', countryCode: 'CY', countryName: 'Cyprus', flag: '🇨🇾' },
  { id: 'Asia/Nicosia', city: 'Nicosia', countryCode: 'CY', countryName: 'Cyprus', flag: '🇨🇾' },
  { id: 'Europe/Prague', city: 'Prague', countryCode: 'CZ', countryName: 'Czechia', flag: '🇨🇿' },
  { id: 'Europe/Copenhagen', city: 'Copenhagen', countryCode: 'DK', countryName: 'Denmark', flag: '🇩🇰' },
  { id: 'Africa/Djibouti', city: 'Djibouti', countryCode: 'DJ', countryName: 'Djibouti', flag: '🇩🇯' },
  { id: 'America/Dominica', city: 'Dominica', countryCode: 'DM', countryName: 'Dominica', flag: '🇩🇲' },
  { id: 'America/Santo_Domingo', city: 'Santo Domingo', countryCode: 'DO', countryName: 'Dominican Republic', flag: '🇩🇴' },
  { id: 'Pacific/Galapagos', city: 'Galapagos', countryCode: 'EC', countryName: 'Ecuador', flag: '🇪🇨' },
  { id: 'America/Guayaquil', city: 'Guayaquil', countryCode: 'EC', countryName: 'Ecuador', flag: '🇪🇨' },
  { id: 'Africa/Cairo', city: 'Cairo', countryCode: 'EG', countryName: 'Egypt', flag: '🇪🇬' },
  { id: 'America/El_Salvador', city: 'El Salvador', countryCode: 'SV', countryName: 'El Salvador', flag: '🇸🇻' },
  { id: 'Africa/Malabo', city: 'Malabo', countryCode: 'GQ', countryName: 'Equatorial Guinea', flag: '🇬🇶' },
  { id: 'Africa/Asmera', city: 'Asmera', countryCode: 'ER', countryName: 'Eritrea', flag: '🇪🇷' },
  { id: 'Europe/Tallinn', city: 'Tallinn', countryCode: 'EE', countryName: 'Estonia', flag: '🇪🇪' },
  { id: 'Africa/Mbabane', city: 'Mbabane', countryCode: 'SZ', countryName: 'Eswatini', flag: '🇸🇿' },
  { id: 'Africa/Addis_Ababa', city: 'Addis Ababa', countryCode: 'ET', countryName: 'Ethiopia', flag: '🇪🇹' },
  { id: 'Atlantic/Stanley', city: 'Stanley', countryCode: 'FK', countryName: 'Falkland Islands', flag: '🇫🇰' },
  { id: 'Atlantic/Faeroe', city: 'Faeroe', countryCode: 'FO', countryName: 'Faroe Islands', flag: '🇫🇴' },
  { id: 'Pacific/Fiji', city: 'Fiji', countryCode: 'FJ', countryName: 'Fiji', flag: '🇫🇯' },
  { id: 'Europe/Helsinki', city: 'Helsinki', countryCode: 'FI', countryName: 'Finland', flag: '🇫🇮' },
  { id: 'Europe/Paris', city: 'Paris', countryCode: 'FR', countryName: 'France', flag: '🇫🇷' },
  { id: 'America/Cayenne', city: 'Cayenne', countryCode: 'GF', countryName: 'French Guiana', flag: '🇬🇫' },
  { id: 'Pacific/Gambier', city: 'Gambier', countryCode: 'PF', countryName: 'French Polynesia', flag: '🇵🇫' },
  { id: 'Pacific/Marquesas', city: 'Marquesas', countryCode: 'PF', countryName: 'French Polynesia', flag: '🇵🇫' },
  { id: 'Pacific/Tahiti', city: 'Tahiti', countryCode: 'PF', countryName: 'French Polynesia', flag: '🇵🇫' },
  { id: 'Indian/Kerguelen', city: 'Kerguelen', countryCode: 'TF', countryName: 'French Southern Territories', flag: '🇹🇫' },
  { id: 'Africa/Libreville', city: 'Libreville', countryCode: 'GA', countryName: 'Gabon', flag: '🇬🇦' },
  { id: 'Africa/Banjul', city: 'Banjul', countryCode: 'GM', countryName: 'Gambia', flag: '🇬🇲' },
  { id: 'Asia/Tbilisi', city: 'Tbilisi', countryCode: 'GE', countryName: 'Georgia', flag: '🇬🇪' },
  { id: 'Europe/Berlin', city: 'Berlin', countryCode: 'DE', countryName: 'Germany', flag: '🇩🇪' },
  { id: 'Europe/Busingen', city: 'Busingen', countryCode: 'DE', countryName: 'Germany', flag: '🇩🇪' },
  { id: 'Africa/Accra', city: 'Accra', countryCode: 'GH', countryName: 'Ghana', flag: '🇬🇭' },
  { id: 'Europe/Gibraltar', city: 'Gibraltar', countryCode: 'GI', countryName: 'Gibraltar', flag: '🇬🇮' },
  { id: 'Europe/Athens', city: 'Athens', countryCode: 'GR', countryName: 'Greece', flag: '🇬🇷' },
  { id: 'America/Danmarkshavn', city: 'Danmarkshavn', countryCode: 'GL', countryName: 'Greenland', flag: '🇬🇱' },
  { id: 'America/Godthab', city: 'Godthab', countryCode: 'GL', countryName: 'Greenland', flag: '🇬🇱' },
  { id: 'America/Scoresbysund', city: 'Scoresbysund', countryCode: 'GL', countryName: 'Greenland', flag: '🇬🇱' },
  { id: 'America/Thule', city: 'Thule', countryCode: 'GL', countryName: 'Greenland', flag: '🇬🇱' },
  { id: 'America/Grenada', city: 'Grenada', countryCode: 'GD', countryName: 'Grenada', flag: '🇬🇩' },
  { id: 'America/Guadeloupe', city: 'Guadeloupe', countryCode: 'GP', countryName: 'Guadeloupe', flag: '🇬🇵' },
  { id: 'Pacific/Guam', city: 'Guam', countryCode: 'GU', countryName: 'Guam', flag: '🇬🇺' },
  { id: 'America/Guatemala', city: 'Guatemala', countryCode: 'GT', countryName: 'Guatemala', flag: '🇬🇹' },
  { id: 'Europe/Guernsey', city: 'Guernsey', countryCode: 'GG', countryName: 'Guernsey', flag: '🇬🇬' },
  { id: 'Africa/Conakry', city: 'Conakry', countryCode: 'GN', countryName: 'Guinea', flag: '🇬🇳' },
  { id: 'Africa/Bissau', city: 'Bissau', countryCode: 'GW', countryName: 'Guinea-Bissau', flag: '🇬🇼' },
  { id: 'America/Guyana', city: 'Guyana', countryCode: 'GY', countryName: 'Guyana', flag: '🇬🇾' },
  { id: 'America/Port-au-Prince', city: 'Port-au-Prince', countryCode: 'HT', countryName: 'Haiti', flag: '🇭🇹' },
  { id: 'America/Tegucigalpa', city: 'Tegucigalpa', countryCode: 'HN', countryName: 'Honduras', flag: '🇭🇳' },
  { id: 'Asia/Hong_Kong', city: 'Hong Kong', countryCode: 'HK', countryName: 'Hong Kong SAR China', flag: '🇭🇰' },
  { id: 'Europe/Budapest', city: 'Budapest', countryCode: 'HU', countryName: 'Hungary', flag: '🇭🇺' },
  { id: 'Atlantic/Reykjavik', city: 'Reykjavik', countryCode: 'IS', countryName: 'Iceland', flag: '🇮🇸' },
  { id: 'Asia/Calcutta', city: 'Calcutta', countryCode: 'IN', countryName: 'India', flag: '🇮🇳' },
  { id: 'Asia/Jakarta', city: 'Jakarta', countryCode: 'ID', countryName: 'Indonesia', flag: '🇮🇩' },
  { id: 'Asia/Jayapura', city: 'Jayapura', countryCode: 'ID', countryName: 'Indonesia', flag: '🇮🇩' },
  { id: 'Asia/Makassar', city: 'Makassar', countryCode: 'ID', countryName: 'Indonesia', flag: '🇮🇩' },
  { id: 'Asia/Pontianak', city: 'Pontianak', countryCode: 'ID', countryName: 'Indonesia', flag: '🇮🇩' },
  { id: 'Asia/Tehran', city: 'Tehran', countryCode: 'IR', countryName: 'Iran', flag: '🇮🇷' },
  { id: 'Asia/Baghdad', city: 'Baghdad', countryCode: 'IQ', countryName: 'Iraq', flag: '🇮🇶' },
  { id: 'Europe/Dublin', city: 'Dublin', countryCode: 'IE', countryName: 'Ireland', flag: '🇮🇪' },
  { id: 'Europe/Isle_of_Man', city: 'Isle of Man', countryCode: 'IM', countryName: 'Isle of Man', flag: '🇮🇲' },
  { id: 'Asia/Jerusalem', city: 'Jerusalem', countryCode: 'IL', countryName: 'Israel', flag: '🇮🇱' },
  { id: 'Europe/Rome', city: 'Rome', countryCode: 'IT', countryName: 'Italy', flag: '🇮🇹' },
  { id: 'America/Jamaica', city: 'Jamaica', countryCode: 'JM', countryName: 'Jamaica', flag: '🇯🇲' },
  { id: 'Asia/Tokyo', city: 'Tokyo', countryCode: 'JP', countryName: 'Japan', flag: '🇯🇵' },
  { id: 'Europe/Jersey', city: 'Jersey', countryCode: 'JE', countryName: 'Jersey', flag: '🇯🇪' },
  { id: 'Asia/Amman', city: 'Amman', countryCode: 'JO', countryName: 'Jordan', flag: '🇯🇴' },
  { id: 'Asia/Almaty', city: 'Almaty', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Asia/Aqtau', city: 'Aqtau', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Asia/Aqtobe', city: 'Aqtobe', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Asia/Atyrau', city: 'Atyrau', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Asia/Oral', city: 'Oral', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Asia/Qostanay', city: 'Qostanay', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Asia/Qyzylorda', city: 'Qyzylorda', countryCode: 'KZ', countryName: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'Africa/Nairobi', city: 'Nairobi', countryCode: 'KE', countryName: 'Kenya', flag: '🇰🇪' },
  { id: 'Pacific/Enderbury', city: 'Enderbury', countryCode: 'KI', countryName: 'Kiribati', flag: '🇰🇮' },
  { id: 'Pacific/Kiritimati', city: 'Kiritimati', countryCode: 'KI', countryName: 'Kiribati', flag: '🇰🇮' },
  { id: 'Pacific/Tarawa', city: 'Tarawa', countryCode: 'KI', countryName: 'Kiribati', flag: '🇰🇮' },
  { id: 'Asia/Kuwait', city: 'Kuwait', countryCode: 'KW', countryName: 'Kuwait', flag: '🇰🇼' },
  { id: 'Asia/Bishkek', city: 'Bishkek', countryCode: 'KG', countryName: 'Kyrgyzstan', flag: '🇰🇬' },
  { id: 'Asia/Vientiane', city: 'Vientiane', countryCode: 'LA', countryName: 'Laos', flag: '🇱🇦' },
  { id: 'Europe/Riga', city: 'Riga', countryCode: 'LV', countryName: 'Latvia', flag: '🇱🇻' },
  { id: 'Asia/Beirut', city: 'Beirut', countryCode: 'LB', countryName: 'Lebanon', flag: '🇱🇧' },
  { id: 'Africa/Maseru', city: 'Maseru', countryCode: 'LS', countryName: 'Lesotho', flag: '🇱🇸' },
  { id: 'Africa/Monrovia', city: 'Monrovia', countryCode: 'LR', countryName: 'Liberia', flag: '🇱🇷' },
  { id: 'Africa/Tripoli', city: 'Tripoli', countryCode: 'LY', countryName: 'Libya', flag: '🇱🇾' },
  { id: 'Europe/Vaduz', city: 'Vaduz', countryCode: 'LI', countryName: 'Liechtenstein', flag: '🇱🇮' },
  { id: 'Europe/Vilnius', city: 'Vilnius', countryCode: 'LT', countryName: 'Lithuania', flag: '🇱🇹' },
  { id: 'Europe/Luxembourg', city: 'Luxembourg', countryCode: 'LU', countryName: 'Luxembourg', flag: '🇱🇺' },
  { id: 'Asia/Macau', city: 'Macau', countryCode: 'MO', countryName: 'Macao SAR China', flag: '🇲🇴' },
  { id: 'Indian/Antananarivo', city: 'Antananarivo', countryCode: 'MG', countryName: 'Madagascar', flag: '🇲🇬' },
  { id: 'Africa/Blantyre', city: 'Blantyre', countryCode: 'MW', countryName: 'Malawi', flag: '🇲🇼' },
  { id: 'Asia/Kuala_Lumpur', city: 'Kuala Lumpur', countryCode: 'MY', countryName: 'Malaysia', flag: '🇲🇾' },
  { id: 'Asia/Kuching', city: 'Kuching', countryCode: 'MY', countryName: 'Malaysia', flag: '🇲🇾' },
  { id: 'Indian/Maldives', city: 'Maldives', countryCode: 'MV', countryName: 'Maldives', flag: '🇲🇻' },
  { id: 'Africa/Bamako', city: 'Bamako', countryCode: 'ML', countryName: 'Mali', flag: '🇲🇱' },
  { id: 'Europe/Malta', city: 'Malta', countryCode: 'MT', countryName: 'Malta', flag: '🇲🇹' },
  { id: 'Pacific/Kwajalein', city: 'Kwajalein', countryCode: 'MH', countryName: 'Marshall Islands', flag: '🇲🇭' },
  { id: 'Pacific/Majuro', city: 'Majuro', countryCode: 'MH', countryName: 'Marshall Islands', flag: '🇲🇭' },
  { id: 'America/Martinique', city: 'Martinique', countryCode: 'MQ', countryName: 'Martinique', flag: '🇲🇶' },
  { id: 'Africa/Nouakchott', city: 'Nouakchott', countryCode: 'MR', countryName: 'Mauritania', flag: '🇲🇷' },
  { id: 'Indian/Mauritius', city: 'Mauritius', countryCode: 'MU', countryName: 'Mauritius', flag: '🇲🇺' },
  { id: 'Indian/Mayotte', city: 'Mayotte', countryCode: 'YT', countryName: 'Mayotte', flag: '🇾🇹' },
  { id: 'America/Bahia_Banderas', city: 'Bahia Banderas', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Cancun', city: 'Cancun', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Chihuahua', city: 'Chihuahua', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Ciudad_Juarez', city: 'Ciudad Juarez', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Hermosillo', city: 'Hermosillo', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Matamoros', city: 'Matamoros', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Mazatlan', city: 'Mazatlan', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Merida', city: 'Merida', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Mexico_City', city: 'Mexico City', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Monterrey', city: 'Monterrey', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Ojinaga', city: 'Ojinaga', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'America/Tijuana', city: 'Tijuana', countryCode: 'MX', countryName: 'Mexico', flag: '🇲🇽' },
  { id: 'Pacific/Kosrae', city: 'Kosrae', countryCode: 'FM', countryName: 'Micronesia', flag: '🇫🇲' },
  { id: 'Pacific/Ponape', city: 'Ponape', countryCode: 'FM', countryName: 'Micronesia', flag: '🇫🇲' },
  { id: 'Pacific/Truk', city: 'Truk', countryCode: 'FM', countryName: 'Micronesia', flag: '🇫🇲' },
  { id: 'Europe/Chisinau', city: 'Chisinau', countryCode: 'MD', countryName: 'Moldova', flag: '🇲🇩' },
  { id: 'Europe/Monaco', city: 'Monaco', countryCode: 'MC', countryName: 'Monaco', flag: '🇲🇨' },
  { id: 'Asia/Hovd', city: 'Hovd', countryCode: 'MN', countryName: 'Mongolia', flag: '🇲🇳' },
  { id: 'Asia/Ulaanbaatar', city: 'Ulaanbaatar', countryCode: 'MN', countryName: 'Mongolia', flag: '🇲🇳' },
  { id: 'Europe/Podgorica', city: 'Podgorica', countryCode: 'ME', countryName: 'Montenegro', flag: '🇲🇪' },
  { id: 'America/Montserrat', city: 'Montserrat', countryCode: 'MS', countryName: 'Montserrat', flag: '🇲🇸' },
  { id: 'Africa/Casablanca', city: 'Casablanca', countryCode: 'MA', countryName: 'Morocco', flag: '🇲🇦' },
  { id: 'Africa/Maputo', city: 'Maputo', countryCode: 'MZ', countryName: 'Mozambique', flag: '🇲🇿' },
  { id: 'Asia/Rangoon', city: 'Rangoon', countryCode: 'MM', countryName: 'Myanmar (Burma)', flag: '🇲🇲' },
  { id: 'Africa/Windhoek', city: 'Windhoek', countryCode: 'NA', countryName: 'Namibia', flag: '🇳🇦' },
  { id: 'Pacific/Nauru', city: 'Nauru', countryCode: 'NR', countryName: 'Nauru', flag: '🇳🇷' },
  { id: 'Asia/Katmandu', city: 'Katmandu', countryCode: 'NP', countryName: 'Nepal', flag: '🇳🇵' },
  { id: 'Europe/Amsterdam', city: 'Amsterdam', countryCode: 'NL', countryName: 'Netherlands', flag: '🇳🇱' },
  { id: 'Pacific/Noumea', city: 'Noumea', countryCode: 'NC', countryName: 'New Caledonia', flag: '🇳🇨' },
  { id: 'Pacific/Auckland', city: 'Auckland', countryCode: 'NZ', countryName: 'New Zealand', flag: '🇳🇿' },
  { id: 'Pacific/Chatham', city: 'Chatham', countryCode: 'NZ', countryName: 'New Zealand', flag: '🇳🇿' },
  { id: 'America/Managua', city: 'Managua', countryCode: 'NI', countryName: 'Nicaragua', flag: '🇳🇮' },
  { id: 'Africa/Niamey', city: 'Niamey', countryCode: 'NE', countryName: 'Niger', flag: '🇳🇪' },
  { id: 'Africa/Lagos', city: 'Lagos', countryCode: 'NG', countryName: 'Nigeria', flag: '🇳🇬' },
  { id: 'Pacific/Niue', city: 'Niue', countryCode: 'NU', countryName: 'Niue', flag: '🇳🇺' },
  { id: 'Pacific/Norfolk', city: 'Norfolk', countryCode: 'NF', countryName: 'Norfolk Island', flag: '🇳🇫' },
  { id: 'Asia/Pyongyang', city: 'Pyongyang', countryCode: 'KP', countryName: 'North Korea', flag: '🇰🇵' },
  { id: 'Europe/Skopje', city: 'Skopje', countryCode: 'MK', countryName: 'North Macedonia', flag: '🇲🇰' },
  { id: 'Pacific/Saipan', city: 'Saipan', countryCode: 'MP', countryName: 'Northern Mariana Islands', flag: '🇲🇵' },
  { id: 'Europe/Oslo', city: 'Oslo', countryCode: 'NO', countryName: 'Norway', flag: '🇳🇴' },
  { id: 'Asia/Muscat', city: 'Muscat', countryCode: 'OM', countryName: 'Oman', flag: '🇴🇲' },
  { id: 'Asia/Karachi', city: 'Karachi', countryCode: 'PK', countryName: 'Pakistan', flag: '🇵🇰' },
  { id: 'Pacific/Palau', city: 'Palau', countryCode: 'PW', countryName: 'Palau', flag: '🇵🇼' },
  { id: 'Asia/Gaza', city: 'Gaza', countryCode: 'PS', countryName: 'Palestinian Territories', flag: '🇵🇸' },
  { id: 'Asia/Hebron', city: 'Hebron', countryCode: 'PS', countryName: 'Palestinian Territories', flag: '🇵🇸' },
  { id: 'America/Panama', city: 'Panama', countryCode: 'PA', countryName: 'Panama', flag: '🇵🇦' },
  { id: 'Pacific/Bougainville', city: 'Bougainville', countryCode: 'PG', countryName: 'Papua New Guinea', flag: '🇵🇬' },
  { id: 'Pacific/Port_Moresby', city: 'Port Moresby', countryCode: 'PG', countryName: 'Papua New Guinea', flag: '🇵🇬' },
  { id: 'America/Asuncion', city: 'Asuncion', countryCode: 'PY', countryName: 'Paraguay', flag: '🇵🇾' },
  { id: 'America/Lima', city: 'Lima', countryCode: 'PE', countryName: 'Peru', flag: '🇵🇪' },
  { id: 'Asia/Manila', city: 'Manila', countryCode: 'PH', countryName: 'Philippines', flag: '🇵🇭' },
  { id: 'Pacific/Pitcairn', city: 'Pitcairn', countryCode: 'PN', countryName: 'Pitcairn Islands', flag: '🇵🇳' },
  { id: 'Europe/Warsaw', city: 'Warsaw', countryCode: 'PL', countryName: 'Poland', flag: '🇵🇱' },
  { id: 'Atlantic/Azores', city: 'Azores', countryCode: 'PT', countryName: 'Portugal', flag: '🇵🇹' },
  { id: 'Europe/Lisbon', city: 'Lisbon', countryCode: 'PT', countryName: 'Portugal', flag: '🇵🇹' },
  { id: 'Atlantic/Madeira', city: 'Madeira', countryCode: 'PT', countryName: 'Portugal', flag: '🇵🇹' },
  { id: 'America/Puerto_Rico', city: 'Puerto Rico', countryCode: 'PR', countryName: 'Puerto Rico', flag: '🇵🇷' },
  { id: 'Asia/Qatar', city: 'Qatar', countryCode: 'QA', countryName: 'Qatar', flag: '🇶🇦' },
  { id: 'Indian/Reunion', city: 'Reunion', countryCode: 'RE', countryName: 'Réunion', flag: '🇷🇪' },
  { id: 'Europe/Bucharest', city: 'Bucharest', countryCode: 'RO', countryName: 'Romania', flag: '🇷🇴' },
  { id: 'Asia/Anadyr', city: 'Anadyr', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Astrakhan', city: 'Astrakhan', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Barnaul', city: 'Barnaul', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Chita', city: 'Chita', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Irkutsk', city: 'Irkutsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Kaliningrad', city: 'Kaliningrad', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Kamchatka', city: 'Kamchatka', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Khandyga', city: 'Khandyga', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Kirov', city: 'Kirov', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Krasnoyarsk', city: 'Krasnoyarsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Magadan', city: 'Magadan', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Moscow', city: 'Moscow', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Novokuznetsk', city: 'Novokuznetsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Novosibirsk', city: 'Novosibirsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Omsk', city: 'Omsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Sakhalin', city: 'Sakhalin', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Samara', city: 'Samara', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Saratov', city: 'Saratov', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Srednekolymsk', city: 'Srednekolymsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Tomsk', city: 'Tomsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Ulyanovsk', city: 'Ulyanovsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Ust-Nera', city: 'Ust-Nera', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Vladivostok', city: 'Vladivostok', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Europe/Volgograd', city: 'Volgograd', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Yakutsk', city: 'Yakutsk', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Asia/Yekaterinburg', city: 'Yekaterinburg', countryCode: 'RU', countryName: 'Russia', flag: '🇷🇺' },
  { id: 'Africa/Kigali', city: 'Kigali', countryCode: 'RW', countryName: 'Rwanda', flag: '🇷🇼' },
  { id: 'Pacific/Apia', city: 'Apia', countryCode: 'WS', countryName: 'Samoa', flag: '🇼🇸' },
  { id: 'Europe/San_Marino', city: 'San Marino', countryCode: 'SM', countryName: 'San Marino', flag: '🇸🇲' },
  { id: 'Africa/Sao_Tome', city: 'Sao Tome', countryCode: 'ST', countryName: 'São Tomé & Príncipe', flag: '🇸🇹' },
  { id: 'Asia/Riyadh', city: 'Riyadh', countryCode: 'SA', countryName: 'Saudi Arabia', flag: '🇸🇦' },
  { id: 'Africa/Dakar', city: 'Dakar', countryCode: 'SN', countryName: 'Senegal', flag: '🇸🇳' },
  { id: 'Europe/Belgrade', city: 'Belgrade', countryCode: 'RS', countryName: 'Serbia', flag: '🇷🇸' },
  { id: 'Indian/Mahe', city: 'Mahe', countryCode: 'SC', countryName: 'Seychelles', flag: '🇸🇨' },
  { id: 'Africa/Freetown', city: 'Freetown', countryCode: 'SL', countryName: 'Sierra Leone', flag: '🇸🇱' },
  { id: 'Asia/Singapore', city: 'Singapore', countryCode: 'SG', countryName: 'Singapore', flag: '🇸🇬' },
  { id: 'America/Lower_Princes', city: 'Lower Princes', countryCode: 'SX', countryName: 'Sint Maarten', flag: '🇸🇽' },
  { id: 'Europe/Bratislava', city: 'Bratislava', countryCode: 'SK', countryName: 'Slovakia', flag: '🇸🇰' },
  { id: 'Europe/Ljubljana', city: 'Ljubljana', countryCode: 'SI', countryName: 'Slovenia', flag: '🇸🇮' },
  { id: 'Pacific/Guadalcanal', city: 'Guadalcanal', countryCode: 'SB', countryName: 'Solomon Islands', flag: '🇸🇧' },
  { id: 'Africa/Mogadishu', city: 'Mogadishu', countryCode: 'SO', countryName: 'Somalia', flag: '🇸🇴' },
  { id: 'Africa/Johannesburg', city: 'Johannesburg', countryCode: 'ZA', countryName: 'South Africa', flag: '🇿🇦' },
  { id: 'Atlantic/South_Georgia', city: 'South Georgia', countryCode: 'GS', countryName: 'South Georgia & South Sandwich Islands', flag: '🇬🇸' },
  { id: 'Asia/Seoul', city: 'Seoul', countryCode: 'KR', countryName: 'South Korea', flag: '🇰🇷' },
  { id: 'Africa/Juba', city: 'Juba', countryCode: 'SS', countryName: 'South Sudan', flag: '🇸🇸' },
  { id: 'Atlantic/Canary', city: 'Canary', countryCode: 'ES', countryName: 'Spain', flag: '🇪🇸' },
  { id: 'Africa/Ceuta', city: 'Ceuta', countryCode: 'ES', countryName: 'Spain', flag: '🇪🇸' },
  { id: 'Europe/Madrid', city: 'Madrid', countryCode: 'ES', countryName: 'Spain', flag: '🇪🇸' },
  { id: 'Asia/Colombo', city: 'Colombo', countryCode: 'LK', countryName: 'Sri Lanka', flag: '🇱🇰' },
  { id: 'America/St_Barthelemy', city: 'St Barthelemy', countryCode: 'BL', countryName: 'St. Barthélemy', flag: '🇧🇱' },
  { id: 'Atlantic/St_Helena', city: 'St Helena', countryCode: 'SH', countryName: 'St. Helena', flag: '🇸🇭' },
  { id: 'America/St_Kitts', city: 'St Kitts', countryCode: 'KN', countryName: 'St. Kitts & Nevis', flag: '🇰🇳' },
  { id: 'America/St_Lucia', city: 'St Lucia', countryCode: 'LC', countryName: 'St. Lucia', flag: '🇱🇨' },
  { id: 'America/Marigot', city: 'Marigot', countryCode: 'MF', countryName: 'St. Martin', flag: '🇲🇫' },
  { id: 'America/Miquelon', city: 'Miquelon', countryCode: 'PM', countryName: 'St. Pierre & Miquelon', flag: '🇵🇲' },
  { id: 'America/St_Vincent', city: 'St Vincent', countryCode: 'VC', countryName: 'St. Vincent & Grenadines', flag: '🇻🇨' },
  { id: 'Africa/Khartoum', city: 'Khartoum', countryCode: 'SD', countryName: 'Sudan', flag: '🇸🇩' },
  { id: 'America/Paramaribo', city: 'Paramaribo', countryCode: 'SR', countryName: 'Suriname', flag: '🇸🇷' },
  { id: 'Arctic/Longyearbyen', city: 'Longyearbyen', countryCode: 'SJ', countryName: 'Svalbard & Jan Mayen', flag: '🇸🇯' },
  { id: 'Europe/Stockholm', city: 'Stockholm', countryCode: 'SE', countryName: 'Sweden', flag: '🇸🇪' },
  { id: 'Europe/Zurich', city: 'Zurich', countryCode: 'CH', countryName: 'Switzerland', flag: '🇨🇭' },
  { id: 'Asia/Damascus', city: 'Damascus', countryCode: 'SY', countryName: 'Syria', flag: '🇸🇾' },
  { id: 'Asia/Taipei', city: 'Taipei', countryCode: 'TW', countryName: 'Taiwan', flag: '🇹🇼' },
  { id: 'Asia/Dushanbe', city: 'Dushanbe', countryCode: 'TJ', countryName: 'Tajikistan', flag: '🇹🇯' },
  { id: 'Africa/Dar_es_Salaam', city: 'Dar es Salaam', countryCode: 'TZ', countryName: 'Tanzania', flag: '🇹🇿' },
  { id: 'Asia/Bangkok', city: 'Bangkok', countryCode: 'TH', countryName: 'Thailand', flag: '🇹🇭' },
  { id: 'Asia/Dili', city: 'Dili', countryCode: 'TL', countryName: 'Timor-Leste', flag: '🇹🇱' },
  { id: 'Africa/Lome', city: 'Lome', countryCode: 'TG', countryName: 'Togo', flag: '🇹🇬' },
  { id: 'Pacific/Fakaofo', city: 'Fakaofo', countryCode: 'TK', countryName: 'Tokelau', flag: '🇹🇰' },
  { id: 'Pacific/Tongatapu', city: 'Tongatapu', countryCode: 'TO', countryName: 'Tonga', flag: '🇹🇴' },
  { id: 'America/Port_of_Spain', city: 'Port of Spain', countryCode: 'TT', countryName: 'Trinidad & Tobago', flag: '🇹🇹' },
  { id: 'Africa/Tunis', city: 'Tunis', countryCode: 'TN', countryName: 'Tunisia', flag: '🇹🇳' },
  { id: 'Europe/Istanbul', city: 'Istanbul', countryCode: 'TR', countryName: 'Türkiye', flag: '🇹🇷' },
  { id: 'Asia/Ashgabat', city: 'Ashgabat', countryCode: 'TM', countryName: 'Turkmenistan', flag: '🇹🇲' },
  { id: 'America/Grand_Turk', city: 'Grand Turk', countryCode: 'TC', countryName: 'Turks & Caicos Islands', flag: '🇹🇨' },
  { id: 'Pacific/Funafuti', city: 'Funafuti', countryCode: 'TV', countryName: 'Tuvalu', flag: '🇹🇻' },
  { id: 'Pacific/Midway', city: 'Midway', countryCode: 'UM', countryName: 'U.S. Outlying Islands', flag: '🇺🇲' },
  { id: 'Pacific/Wake', city: 'Wake', countryCode: 'UM', countryName: 'U.S. Outlying Islands', flag: '🇺🇲' },
  { id: 'America/St_Thomas', city: 'St Thomas', countryCode: 'VI', countryName: 'U.S. Virgin Islands', flag: '🇻🇮' },
  { id: 'Africa/Kampala', city: 'Kampala', countryCode: 'UG', countryName: 'Uganda', flag: '🇺🇬' },
  { id: 'Europe/Kiev', city: 'Kiev', countryCode: 'UA', countryName: 'Ukraine', flag: '🇺🇦' },
  { id: 'Europe/Simferopol', city: 'Simferopol', countryCode: 'UA', countryName: 'Ukraine', flag: '🇺🇦' },
  { id: 'Asia/Dubai', city: 'Dubai', countryCode: 'AE', countryName: 'United Arab Emirates', flag: '🇦🇪' },
  { id: 'Europe/London', city: 'London', countryCode: 'GB', countryName: 'United Kingdom', flag: '🇬🇧' },
  { id: 'America/Adak', city: 'Adak', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Anchorage', city: 'Anchorage', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/North_Dakota/Beulah', city: 'Beulah', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Boise', city: 'Boise', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/North_Dakota/Center', city: 'Center', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Chicago', city: 'Chicago', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Denver', city: 'Denver', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Detroit', city: 'Detroit', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'Pacific/Honolulu', city: 'Honolulu', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indianapolis', city: 'Indianapolis', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Juneau', city: 'Juneau', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Knox', city: 'Knox', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Los_Angeles', city: 'Los Angeles', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Louisville', city: 'Louisville', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Marengo', city: 'Marengo', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Menominee', city: 'Menominee', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Metlakatla', city: 'Metlakatla', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Kentucky/Monticello', city: 'Monticello', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/North_Dakota/New_Salem', city: 'New Salem', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/New_York', city: 'New York', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Nome', city: 'Nome', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Petersburg', city: 'Petersburg', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Phoenix', city: 'Phoenix', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Sitka', city: 'Sitka', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Tell_City', city: 'Tell City', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Vevay', city: 'Vevay', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Vincennes', city: 'Vincennes', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Indiana/Winamac', city: 'Winamac', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Yakutat', city: 'Yakutat', countryCode: 'US', countryName: 'United States', flag: '🇺🇸' },
  { id: 'America/Montevideo', city: 'Montevideo', countryCode: 'UY', countryName: 'Uruguay', flag: '🇺🇾' },
  { id: 'Asia/Samarkand', city: 'Samarkand', countryCode: 'UZ', countryName: 'Uzbekistan', flag: '🇺🇿' },
  { id: 'Asia/Tashkent', city: 'Tashkent', countryCode: 'UZ', countryName: 'Uzbekistan', flag: '🇺🇿' },
  { id: 'Pacific/Efate', city: 'Efate', countryCode: 'VU', countryName: 'Vanuatu', flag: '🇻🇺' },
  { id: 'Europe/Vatican', city: 'Vatican', countryCode: 'VA', countryName: 'Vatican City', flag: '🇻🇦' },
  { id: 'America/Caracas', city: 'Caracas', countryCode: 'VE', countryName: 'Venezuela', flag: '🇻🇪' },
  { id: 'Asia/Saigon', city: 'Saigon', countryCode: 'VN', countryName: 'Vietnam', flag: '🇻🇳' },
  { id: 'Pacific/Wallis', city: 'Wallis', countryCode: 'WF', countryName: 'Wallis & Futuna', flag: '🇼🇫' },
  { id: 'Africa/El_Aaiun', city: 'El Aaiun', countryCode: 'EH', countryName: 'Western Sahara', flag: '🇪🇭' },
  { id: 'Asia/Aden', city: 'Aden', countryCode: 'YE', countryName: 'Yemen', flag: '🇾🇪' },
  { id: 'Africa/Lusaka', city: 'Lusaka', countryCode: 'ZM', countryName: 'Zambia', flag: '🇿🇲' },
  { id: 'Africa/Harare', city: 'Harare', countryCode: 'ZW', countryName: 'Zimbabwe', flag: '🇿🇼' },
];
